# (C) Copyright 2019 Hewlett Packard Enterprise Development LP
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: prometheus
      protocol: TCP
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "name" . }}
